name: Create RIO package
description: 'creates a package on the platform and saves package details in file'
runs:
  using: composite
  steps:
    - id: create-package
      run: python .github/scripts/create_package.py .github/app_config/details/build_details.yaml .github/app_config/package.yaml
      shell: bash