name: Create RIO package
description: 'creates a package on the platform and saves package details in file'
runs:
  using: composite
  steps:
    - id: create-package
      run: .github/scripts/create_package/create_package.sh -f .github/scripts/app_config/details/build_details.yaml .github/scripts/app_config/package.yaml
      shell: bash